name: C/C++ module CI with CMake and Ninja

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build

    - name: Install Software to manage repositories
      run: sudo apt-get install -y software-properties-common lsb-release wget

    - name: Add LLVM gpg key
      run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -


    - name: Add LLVM repository
      run: sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main"

    - name: Update Package lists
      run: sudo apt-get update


    - name: Update clang
      run: sudo apt-get install clang-18

    - name: set clang 18 as default
      run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100

    - name: Update clang tools
      run: sudo apt-get install clang-tools-18

    - name: Update to ninja 1.11.1
      run: sudo wget https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip && sudo unzip ninja-linux.zip -d /usr/local/bin/

    - name: Download CMake 3.29.3
      run: wget https://github.com/Kitware/CMake/releases/download/v3.29.3/cmake-3.29.3-linux-x86_64.sh && chmod +x cmake-3.29.3-linux-x86_64.sh

    - name: Run the CMake install script
      run: sudo mkdir /opt/cmake-3.29.3 && sudo ./cmake-3.29.3-linux-x86_64.sh --prefix=/opt/cmake-3.29.3 --skip-license

    - name: Link Cmake binaries to their usual path
      run: sudo ln -sf /opt/cmake-3.29.3/bin/* /usr/local/bin/

    - name: Emit clang++-18 version
      run: clang++-18 --version

    - name: Emit clang version
      run: clang --version

    - name: Emit cmake version
      run: cmake --version

    - name: Emit ninja version
      run: ninja --version

    - name: Configure with CMake and Clang++-18
      run: CXX=clang++-18 CC=clang cmake -S . -B build -G Ninja

    - name: Build
      run: CXX=clang++-18 CC=clang cmake --build build

    - name: Test
      run: ./build/unit_tests
